
name: Setup Node and pmpn
description: Composite action that sets up pnpn and installs dependencies
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - uses: pnpm/action-setup@v2.2.4
    - run: pnpm install --frozen-lockfile
